// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"
)

type Post struct {
	ID        int32     `json:"id"`
	UserID    int32     `json:"user_id"`
	Title     string    `json:"title"`
	Content   string    `json:"content"`
	Votes     int32     `json:"votes"`
	UpdatedAt time.Time `json:"updated_at"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID        int32     `json:"id"`
	Username  string    `json:"username"`
	Email     string    `json:"email"`
	Password  string    `json:"password"`
	UpdatedAt time.Time `json:"updated_at"`
	CreatedAt time.Time `json:"created_at"`
}

type Vote struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
	PostID int32 `json:"post_id"`
	// true if liked and false if disliked. No rows if no response
	Voted bool `json:"voted"`
}
