// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"
)

type Like struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
	PostID int32 `json:"post_id"`
	// true if liked and false if disliked. No rows if no response
	Liked   bool         `json:"liked"`
	LikedAt sql.NullTime `json:"liked_at"`
}

type Post struct {
	ID        int32     `json:"id"`
	UserID    int32     `json:"user_id"`
	Title     string    `json:"title"`
	Desc      string    `json:"desc"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID        int32     `json:"id"`
	FullName  string    `json:"full_name"`
	CreatedAt time.Time `json:"created_at"`
}
